apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-log
          emptyDir: {}
        - name: config-volume
          configMap:
            name: logoutput-config
      containers:
        - name: log-writer
          image: log-writer:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "writer.py"]
          volumeMounts:
            - name: shared-log
              mountPath: /shared
        - name: log-reader
          image: log-reader:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "reader.py"]
          env:
            - name: PORT
              value: "8000"
            - name: PINGPONG_URL
              value: "http://pingpong-service.exercises:80/pings"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logoutput-config
                  key: MESSAGE
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8000
          volumeMounts:
            - name: shared-log
              mountPath: /shared
            - name: config-volume
              mountPath: /config