apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      containers:
        - name: writer
          image: logoutput:1
          imagePullPolicy: IfNotPresent
          command: ["python", "writer.py"]
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logoutput-config
                  key: MESSAGE
            - name: PINGPONG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: logoutput-pingpong-config
                  key: PINGPONG_SERVICE_URL
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
            - name: config-volume
              mountPath: /config
        - name: reader
          image: logoutput:1
          imagePullPolicy: IfNotPresent
          command: ["python", "reader.py"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: logoutput-pingpong-config
                  key: PORT
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
      volumes:
        - name: shared-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            name: logoutput-config