apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logoutput-ingress
spec:
  rules:
    - host: logoutput.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: logoutput-service
                port:
                  number: 80
