apiVersion: v1
kind: Service
metadata:
  name: logoutput-service
spec:
  type: ClusterIP
  selector:
    app: hashgenerator
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
