apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wikipedia-route
  namespace: default
spec:
  parentRefs:
    - name: wikipedia-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: wikipedia-svc
          port: 80

