apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pingpong-cpu-usage
  namespace: exercises
spec:
  metrics:
    - name: namespace-cpu-usage
      initialDelay: 2m
      successCondition: result < 0.1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.prometheus.svc.cluster.local:9090
          query: |
            sum(rate(container_cpu_usage_seconds_total{namespace="exercises",container!="",image!=""}[5m]))
