apiVersion: v1
kind: ConfigMap
metadata:
  name: pingpong-config
  namespace: exercises
data:
  PORT: "8000"
  DB_HOST: "postgres-service.exercises"
  DB_PORT: "5432"
  DB_NAME: "pingpongdb"
  DB_USER: "pingponguser"
  DB_PASSWORD: "pingpongpass"