apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: todo-wiki-cronjob
spec:
  schedule: "0 * * * *"  # Every hour at minute 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wiki-todo
              image: PROJECT/TODO_CRONJOB
              env:
                - name: BACKEND_URL
                  value: "http://todo-backend-svc:80"
          restartPolicy: OnFailure

