apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - configmap.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - cronjob.yaml
  - backup-cronjob.yaml
images:
  - name: PROJECT/TODO_BACKEND
    newName: gcr.io/dwk-gke-484516/todo-backend
  - name: PROJECT/TODO_CRONJOB
    newName: gcr.io/dwk-gke-484516/todo-cronjob
  - name: PROJECT/TODO_BACKUP
    newName: gcr.io/dwk-gke-484516/todo-backup

