apiVersion: v1
kind: Secret
metadata:
  namespace: project
  name: todo-postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: "todouser"
  POSTGRES_PASSWORD: "todopassword"
  POSTGRES_DB: "tododb"

