apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app-dep
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: todo-images
          persistentVolumeClaim:
            claimName: todo-images-pvc
      containers:
        - name: todo-app
          image: PROJECT/TODO_APP
          resources:
            requests:
              cpu: "1m"
              memory: "8Mi"
            limits:
              cpu: "25m"
              memory: "32Mi"
          envFrom:
            - configMapRef:
                name: todo-app-configmap
          volumeMounts:
            - name: todo-images
              mountPath: /usr/src/app/images

