apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-wikipedia-todo
  namespace: project
spec:
  schedule: "0 * * * *"  # Every hour at minute 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: random-todo
            image: random-todo:1
            imagePullPolicy: IfNotPresent
            env:
            - name: BACKEND_URL
              value: "http://todo-backend-service.project:80"
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
