apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
  namespace: project
data:
  PORT: "8000"
  DB_HOST: "postgres-stset-0.postgres-service.project"
  DB_PORT: "5432"
  DB_NAME: "tododb"
  DB_USER: "todouser"
  NATS_URL: "nats://my-nats.default.svc.cluster.local:4222"
  BROADCAST_SUBJECT: "todo.events"